# Generated by Django 3.2.8 on 2021-10-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, verbose_name='Silka ')),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Convert',
                'verbose_name_plural': 'Converts',
            },
        ),
    ]
